#!/bin/bash
# pull-anthropic-metadata.sh
# 
# Pulls Anthropic model metadata from official docs via Firecrawl,
# extracts beta headers and model capabilities, outputs TOML.
#
# Requires: FIRECRAWL_API_KEY, jq, curl
#
# Usage: ./pull-anthropic-metadata.sh > anthropic-models.toml

set -euo pipefail

DOCS_DIR="${DOCS_DIR:-$(mktemp -d)}"
FIRECRAWL_API_KEY="${FIRECRAWL_API_KEY:?FIRECRAWL_API_KEY required}"

stderr() { echo "$@" >&2; }

# -----------------------------------------------------------------------------
# Scrape a URL to markdown
# -----------------------------------------------------------------------------
scrape() {
  local url="$1"
  local outfile="$2"
  stderr "Scraping $url..."
  curl -s -X POST "https://api.firecrawl.dev/v1/scrape" \
    -H "Authorization: Bearer ${FIRECRAWL_API_KEY}" \
    -H "Content-Type: application/json" \
    -d "{\"url\": \"$url\", \"formats\": [\"markdown\"]}" \
    | jq -r '.data.markdown // empty' > "$outfile"
  
  if [[ ! -s "$outfile" ]]; then
    stderr "Warning: Empty response for $url"
  fi
}

# -----------------------------------------------------------------------------
# Pull all docs
# -----------------------------------------------------------------------------
stderr "=== Pulling Anthropic docs to $DOCS_DIR ==="

scrape "https://platform.claude.com/docs/en/api/go/beta/files/list" "$DOCS_DIR/go-sdk-betas.md"
scrape "https://platform.claude.com/docs/en/about-claude/models/overview" "$DOCS_DIR/models.md"
scrape "https://platform.claude.com/docs/en/build-with-claude/extended-thinking" "$DOCS_DIR/thinking.md"
scrape "https://platform.claude.com/docs/en/build-with-claude/context-windows" "$DOCS_DIR/context.md"
scrape "https://platform.claude.com/docs/en/build-with-claude/computer-use" "$DOCS_DIR/computer-use.md"
scrape "https://platform.claude.com/docs/en/about-claude/pricing" "$DOCS_DIR/pricing.md"

# -----------------------------------------------------------------------------
# Extract beta headers from Go SDK
# -----------------------------------------------------------------------------
stderr "=== Extracting beta headers ==="

# Handle escaped underscores from markdown (\_)
BETA_HEADERS=$(grep -oE '"[a-z0-9-]+-[0-9]{4}-[0-9]{2}-[0-9]{2}"' "$DOCS_DIR/go-sdk-betas.md" \
  | tr -d '"' \
  | sort -u)

# -----------------------------------------------------------------------------
# Extract model IDs
# -----------------------------------------------------------------------------
stderr "=== Extracting model info ==="

# Models that support 1M context
MODELS_1M=$(grep -i "1M token context\|1-million token\|context-1m" "$DOCS_DIR/context.md" \
  | grep -oiE "claude[- ](opus|sonnet|haiku)[- ][0-9.]+" \
  | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | sort -u || true)

# Models with extended thinking
MODELS_THINKING=$(grep -iE "Extended thinking.*(supported|available)" "$DOCS_DIR/thinking.md" \
  | grep -oiE "claude[- ][a-z0-9.-]+" \
  | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | sort -u || true)

# Computer use versions
COMPUTER_V3=$(grep -i "computer-use-2025-11-24" "$DOCS_DIR/computer-use.md" \
  | grep -oiE "claude[- ](opus|sonnet)[- ][0-9.]+" \
  | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | sort -u || true)

# -----------------------------------------------------------------------------
# Output TOML
# -----------------------------------------------------------------------------
stderr "=== Generating TOML ==="

cat << 'TOML_HEADER'
# Anthropic Model Capabilities Registry
# Auto-generated by pull-anthropic-metadata.sh
TOML_HEADER

echo "# Generated: $(date -Iseconds)"
echo ""
echo "[meta]"
echo "version = \"1\""
echo "generated = \"$(date -Iseconds)\""
echo "source = \"platform.claude.com/docs\""
echo ""

# Beta headers section
echo "# ============================================================================="
echo "# BETA HEADERS (extracted from Go SDK)"
echo "# ============================================================================="
echo ""
echo "[beta_headers]"
for header in $BETA_HEADERS; do
  # Convert header name to description (rough)
  desc=$(echo "$header" | sed 's/-[0-9]*-[0-9]*-[0-9]*$//' | tr '-' ' ')
  echo "\"$header\" = \"$desc\""
done
echo ""

# Core parameters
echo "# ============================================================================="
echo "# CORE PARAMETERS"
echo "# ============================================================================="
echo ""
cat << 'CORE_PARAMS'
[core_parameters]
supported = ["temperature", "top_p", "top_k", "max_tokens", "stop_sequences", "stream", "system", "tools", "tool_choice"]
not_supported = ["frequency_penalty", "presence_penalty", "repetition_penalty", "min_p", "seed", "logprobs"]
CORE_PARAMS
echo ""

# Models section header
echo "# ============================================================================="
echo "# MODELS"
echo "# ============================================================================="
echo "# NOTE: This is a skeleton. Manual review recommended for accuracy."
echo ""

# Generate model stubs from extracted info
stderr "Models with 1M context: $MODELS_1M"
stderr "Models with thinking: $MODELS_THINKING"
stderr "Models with computer v3: $COMPUTER_V3"

# Known models (hardcoded structure, filled from extractions)
for model in "claude-opus-4-6" "claude-sonnet-4-6" "claude-opus-4-5" "claude-sonnet-4-5" "claude-haiku-4-5" "claude-sonnet-4" "claude-opus-4"; do
  echo "[models.\"$model\"]"
  echo "name = \"$(echo $model | sed 's/-/ /g' | sed 's/\b\(.\)/\u\1/g')\""
  
  # Check 1M support
  if echo "$MODELS_1M" | grep -q "$model"; then
    echo "context_1m = true"
  else
    echo "context_1m = false"
  fi
  
  # Check computer use version
  if echo "$COMPUTER_V3" | grep -q "$model"; then
    echo "computer_use = \"computer-use-2025-11-24\""
  else
    echo "computer_use = \"computer-use-2025-01-24\""
  fi
  
  echo ""
done

stderr "=== Done. Review output for accuracy. ==="
stderr "Raw docs saved to: $DOCS_DIR"
